name: Documentation Generation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Generate Rust Documentation
      run: cargo doc --no-deps

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Create Doc Conversion Script
      run: |
        cat > convert_docs.py << 'EOL'
        import os
        import json
        from pathlib import Path
        from jinja2 import Template
        from anthropic import Anthropic
        
        def read_html_files(dir_path):
            contents = []
            for path in Path(dir_path).rglob('*.html'):
                with open(path, 'r', encoding='utf-8') as f:
                    contents.append({
                        'path': str(path),
                        'content': f.read()
                    })
            return contents
        
        def main():
            # Read all HTML documentation files
            doc_files = read_html_files('target/doc/simple_mpi')
            
            # Combine all HTML content
            all_docs = '\n\n'.join(f"# File: {Path(f['path']).name}\n{f['content']}" 
                                 for f in doc_files)
            
            # Read the template
            with open('.github/workflows/prompt.jinja', 'r') as f:
                template = Template(f.read())
            
            # Render the template
            prompt = template.render(documentation=all_docs)
            
            # Create docs directory
            os.makedirs('markdown_docs', exist_ok=True)
            
            # Convert to markdown using Claude
            anthropic = Anthropic(api_key=os.environ['ANTHROPIC_API_KEY'])
            
            print('Converting documentation to markdown...')
            message = anthropic.messages.create(
                model="claude-3-5-sonnet-20241022",
                max_tokens=1000000,
                messages=[{
                    "role": "user",
                    "content": prompt
                }]
            )
            
            # Save the markdown
            with open('markdown_docs/documentation.md', 'w') as f:
                f.write(message.content[0].text)
            print('Created unified markdown documentation')
        
        if __name__ == '__main__':
            main()
        EOL

    - name: Install Dependencies
      run: pip install anthropic jinja2

    - name: Convert Documentation to Markdown
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: python convert_docs.py

    - name: Upload HTML Documentation
      uses: actions/upload-artifact@v4
      with:
        name: rust-docs-html
        path: target/doc/simple_mpi
        
    - name: Upload Markdown Documentation
      uses: actions/upload-artifact@v4
      with:
        name: rust-docs-markdown
        path: markdown_docs
