name: Documentation Generation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Generate Rust Documentation
      run: cargo doc --no-deps

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: pip install openai jinja2 pydantic

    - name: Convert Documentation
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python .github/workflows/doc_converter.py

    - name: Upload HTML Documentation
      uses: actions/upload-artifact@v4
      with:
        name: rust-docs-html
        path: target/doc/simple_mpi
        
    - name: Upload Documentation
      uses: actions/upload-artifact@v4
      with:
        name: rust-docs
        path: markdown_docs
